### PR TITLE
Placeholder fix

### PR DESCRIPTION
**Pull request by LuisONasc**
This is my two cents for issue #11.

### CODE REVIEW

**Comment by AuHau** [comment]
Thanks for the contribution!

But before merging this, can you please fix the tests? TravisCI is unfortunately complaining... :-/

**Comment by AuHau** [comment]
@taavs any update on this?

**Comment by LuisONasc** [comment]
Sorry about the delay. I forgot to add the src/picker.js file in the first commit. Should be all good now.

**Comment by AuHau** [comment]
Great! Thanks 👍

**Pull request merged**
