### PR TITLE
Trigger select onChange

### PR DESCRIPTION
**Pull request by poocart**

### CODE REVIEW

**Comment by AuHau** [comment]
Hey there!
Thanks for your PR! Events support is definitely must have and planned, so thanks for help!
But there are few things which needs to be still done, before accepting your PR:
- More events - I think there should be more events. Do you have some suggestions?
- Prefix - the event's name should be prefixed to prevent conflicts (I would suggest prefix "sp-")
- Documentation - the events have to be documented
- Tests - tests are still not pushed to master branch, but I would like to finish basic tests and push them in to master this week

Would you like to incorporate these points? Otherwise I will work on it myself this or next week.

**Comment by poocart** [comment]
Hello,

I will not have enough time on these in such short period so looking forward for your changes.

Good luck!

**Comment by AuHau** [comment]
I see, no problem!

Do you have some suggestion about what events should be supported? I am currently not completely sure for what kind of events I should aim for.

So far only one which is sure is the `change` event you proposed, then I was thinking about `open`/`close` events for the dropdown menu, but now I am not sure if it will be needed...

**Comment by poocart** [comment]
Hey!

I think you should concentrate on all select input default events at first.
Then move on with custom ones (on close, on open, on pick).

I would really be glad to help you, however, I will be busy for about a
month, however, later I can help you with my PR's.

Let's keep in touch!

P. S. Do you have full-time working position and on what programming
languages do you work? Maybe I can offer some freelance projects depending
on your experience and knowledge.

2016-04-27 10:43 GMT+03:00 Adam Uhlíř notifications@github.com:

**Comment by AuHau** [comment]
Hey there again!

that sounds reasonable! I will have look on it.
No problem, I am happy that I can at least consult things with somebody :-)

Currently I am studying, so no - no full-time work. I am working as front dev on one project as freelancer, but nothing too big. I have experiences both in backend and frontend, but more prefer to work on backend. More about me, languages I am working with and my references here: http://adam-uhlir.me/ 
But now during the summer I won't have much free time, but than later on during autumn I would be interested in some work if you would be interested in cooperation with me!

Take care!

**Pull request closed without merging**
